prefer-workspace-packages: true
packages:
  - 'packages/components/*'
  - 'packages/plugins/*'
  - 'packages/tools/*'
  - 'packages/pangu/*'
  - 'packages/qiyuan/*'
  - 'website'
  - 'example/**'
  - 'fixtures/**'
