/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
    components: [
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: ['intro/components'],
        },
        {
            type: 'category',
            label: 'Components',
            collapsed: false,
            items: [
                'components/react-lazy-load-image/index',
                'components/react-waline-client/index',
            ],
        },
    ],
    pangu: [
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: ['intro/pangu'],
        },
        {
            type: 'category',
            label: 'PanGu',
            collapsed: false,
            items: ['pangu/pangu/index'],
        },
    ],
    plugins: [
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: ['intro/plugins'],
        },
        {
            type: 'category',
            label: 'Plugins',
            collapsed: false,
            items: [
                'plugins/changelog-montage/index',
                'plugins/rollup-plugin-generate-style/index',
            ],
        },
    ],
};

module.exports = sidebars;
